apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-demo-deployment
spec:
  selector:
    matchLabels:
      app: argocd-demo
      version: v01
  replicas: 2
  template:
    metadata:
      labels:
        app: argocd-demo
        version: v01
    spec:
      containers:
      - name: argocd-demo
        image: aveek123456/argocd:1.1
        ports:
        - containerPort: 80
        resources:
         limits: 
          memory: 400Mi
         requests:
          cpu: 200m
          memory: 400Mi
        livenessProbe:
         httpGet:
          path: /
          port: 80
         initialDelaySeconds: 5000
         periodSeconds: 30    